### ISSUE TITLE
JMeter throws an "Unknown argument" error while assessing Teastore application

### ISSUE THREAD

**Issue by RaymondSWE** [cau-se/theodolite#21]
I've encountered an issue with JMeter during my tests. Specifically, when attempting to load tests, I receive the following error: "An error occurred: Unknown arg: -t.", this issue leads to a pod crash. To troubleshoot, I've tried executing commands directly within the container to see which argument is invalid and adjusting the YAML configuration to use absolute paths, but the issue persists.

I'm just reaching out to ask if you've had this problem before or if you might have any suggestions on how it can help you resolve it. Any guidance you could provide would be appreciated.

**Comment by SoerenHenning** [comment]
Thanks @RaymondSWE for reporting this issue. I was able to reproduce it and it seems there was a change in how Kubernetes reads the YAML file. I think it should be solved by replacing the `>` with `|` in line 29 of the `jmeter.yaml` file. That is, the file should then look like this:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jmeter
  annotations:
    openservicemesh.io/sidecar-injection: enabled
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teastore
      app2: jmeter
      app.kubernetes.io/name: jmeter
      app.kubernetes.io/component: load-gen
  template:
    metadata:
      labels:
        monitoring: enabled
        app: teastore
        app2: jmeter
        app.kubernetes.io/name: jmeter
        app.kubernetes.io/component: load-gen
    spec:
      containers:
        - name: jmeter
          image: justb4/jmeter:5.4
          command: [ "/bin/bash", "-c", "--" ]
          args:
            - |
              java -jar bin/ApacheJMeter.jar \
              -t profile/teastore_browse_nogui.jmx \
              -Jhostname teastore-webui \
              -Jport 8080 -JnumUser $NUM_USERS \
              -JrampUp 1 -l mylogfile.log -n
          env:
            - name: NUM_USERS
              value: "1"
          volumeMounts:
          - name: jmeter-profile
            mountPath: /opt/apache-jmeter-5.4.3/profile
      volumes:
        - name: jmeter-profile
          configMap:
            name: teastore-jmeter-browse
```

Can you check if this solves it for you?
